version: "3"

networks:
  micronaut:
    driver: bridge

services:
  mongo:
    image: mongo:3
#    ports:
#      - "27017:27017"
    networks:
      - micronaut
  zookeeper:
    image: zookeeper:3.3
    networks:
      micronaut:
        aliases:
        - zookeeper
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - ZOOKEEPER_CONNECTION_TIMEOUT_MS=180000
      - KAFKA_CREATE_TOPICS=notifications:1:1
    ports:
      - "9092:9092"
    networks:
      micronaut:
        aliases:
        - kafka

  eureka:
    image: eureka:0.1
    ports:
      - "8761:8761"
    networks:
      - micronaut
  gateway:
    image: gateway:0.1
    environment:
      - EUREKA_HOST=eureka
    depends_on:
      - eureka
    ports:
      - "9000:9000"
    networks:
      - micronaut
  notifications:
    image: notifications:0.1
    environment:
      - EUREKA_HOST=eureka
      - MICRONAUT_SERVER_HOST=notifications
    depends_on:
      - mongo
      - kafka
      - eureka
      - gateway
    ports:
      - "8081:8081"
    networks:
      micronaut:
        aliases:
          - NOTIFICATIONS
  hello:
    image: hello:0.1
    environment:
      - EUREKA_HOST=eureka
      - MICRONAUT_SERVER_HOST=hello
    depends_on:
      - kafka
      - eureka
      - gateway
    ports:
      - "8082:8082"
    networks:
      micronaut:
        aliases:
          - HELLO
