micronaut:
    application:
        name: gr8crm-service
    server:
        port: 8083
    health:
        monitor:
            enabled: true
            interval: 15s
            initial-delay: 30s

endpoints:
    health:
        enabled: true
        sensitive: false
        details-visible: ANONYMOUS

eureka:
    client:
        registration:
            enabled: true
            fail-fast: false
            retry-count: 8
            retry-delay: 5s
        defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"

kafka:
    bootstrap:
        servers: kafka:9092
